// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetRequests() {
  return window['go']['main']['App']['GetRequests']();
}

export function GetVariables() {
  return window['go']['main']['App']['GetVariables']();
}

export function ResetData() {
  return window['go']['main']['App']['ResetData']();
}

export function SaveFolders(arg1) {
  return window['go']['main']['App']['SaveFolders'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}

export function SaveVariables(arg1) {
  return window['go']['main']['App']['SaveVariables'](arg1);
}

export function SendRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function WSClose(arg1) {
  return window['go']['main']['App']['WSClose'](arg1);
}

export function WSConnect(arg1, arg2) {
  return window['go']['main']['App']['WSConnect'](arg1, arg2);
}

export function WSSend(arg1, arg2) {
  return window['go']['main']['App']['WSSend'](arg1, arg2);
}
